### ISSUE TITLE
mismatch FAT on unlaunch

### ISSUE THREAD

**Issue by sirpugstudios** [Epicpkmn11/NTM#1]
so i tried using this and i am pretty new to this so i dont know what it means by mismatch FAT files and so i searched it up and it said to use this but in order to use this i have to install unlaunch but i cant because of that issue

**Comment by Epicpkmn11** [comment]
Whoops, completely forgot about that feature when disabling running without Unlaunch. Use the latest commit and it'll offer to fix FAT copy mismatch.
