### ISSUE TITLE
Install system update

### ISSUE THREAD

**Issue by FerdinandoPH** [Epicpkmn11/NTM#2]
I'm trying to install the 1.4.5 system update to my dsi, but, despite being a .app format downloaded from NUS, the title manager says that it's not a dsi rom and won't let me install lit. Is this a bug, or do I need to use a different program for installing software updates?

**Comment by Epicpkmn11** [comment]
system updates aren't really able to be packed to .app, you [shouldn't really update](https://dsi.cfw.guide/faq.html#should-i-do-a-system-update), but if you really want to just get it from System Settings.
